### ISSUE TITLE
Option to allow return null from read if file does not exist

### ISSUE THREAD

**Issue by vjpr** [SBoudrias/mem-fs-editor#60] opened 2016-05-28 04:43 UTC
This would save having to write `this.fs.exists() && this.fs.read()`.

Can't think of a good name. Something like `{nullIfNotExists}` or `{throws: false}`.

The current design with the `defaults` option assumes that when you read a file you want to create it.

But say you want to read a file, get its contents, run some logic to decide which location to write it to, then it becomes more verbose. 

I am writing idempotent generators for yeoman and this is a common practice for me.

E.g.

```
docs/LICENSE.md
LICENSE.md
```

Try to read each file, merge contents/decide which contents to use, then write file depending on option.

**Comment by vjpr** [comment] 2016-05-29 09:19
https://github.com/jprichardson/node-fs-extra#readjsonfile-options-callback

The `throws` option from fs-extra is what I am looking for.

**Comment by SBoudrias** [comment] 2016-06-07 18:13
So the issue is that the `default` option create a file in the read location?

That sounds like a bug to me. Fixing this would fix your use case right?

**Comment by vjpr** [comment] 2016-06-08 09:00
> That sounds like a bug to me. Fixing this would fix your use case right?

Yep. If you are reading a file, it should never create a file.

But it would be great to have a `throws` option too, such that it returns null if the file does not exist.

**Comment by SBoudrias** [comment] 2017-01-27 07:46
Hey, been working on a new release today. I've been looking at this issue again and turns out we do "create" a file entry in mem-fs, but unless file objects are marked as modified or new, they're not committed to disk later on.

In the case of read, we do create a new file pointer to the location, but that new file is neither marked as new or modified and as such it should be transparent to the end user.

As such, I think the only issue is that the read function was trying to be too smart and did mutate the file pointer maybe causing side effects. So I implemented a fix that when a file doesn't exists, the `options.defaults` values can be of any types.

This will allow you to write `this.fs.read('does-not-exist', {defaults: null})` without having an error thrown out.

**Closed** 2017-01-27 07:46 UTC
