### ISSUE TITLE
why assert files' length in copy function？

### ISSUE THREAD

**Issue by tarol** [SBoudrias/mem-fs-editor#104] opened 2018-04-27 07:26 UTC
if I use glob pattern, sometimes get nothing matched, and i don't want to catch this error, can this assert be configurable？

**Comment by SBoudrias** [comment] 2018-04-27 08:35
I think this makes sense. Want to send a PR?

**Comment by SBoudrias** [comment] 2018-05-06 17:33
Duplicate of #82. I'll close this one and keep the older issue open.

**Closed by SBoudrias** 2018-05-06 17:33 UTC
