### ISSUE TITLE
fs.copyTpl throws error with recursive globs (**/*)

### ISSUE THREAD

**Issue by timkelty** [SBoudrias/mem-fs-editor#19] opened 2015-01-16 13:58 UTC
Originally posted here: https://github.com/yeoman/generator/issues/735
@blai suggested I post this here, as it may be a `mem-fs-editor` bug.

Ran into this here: https://github.com/timkelty/generator-craft-plugin

```
      this.fs.copyTpl(
        this.templatePath('pluginhandle/**/*'),
        this.destinationPath(pluginDest),
        this
      );
```

This _was_ working rather recently, but with a freshly re-installed yo, I get this:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'toString' of null
    at copy.process (/Users/timkelty/Repos/generator-craft-plugin/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:11:34)
    at applyProcessingFunc (/Users/timkelty/Repos/generator-craft-plugin/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:12:16)
    at EditionInterface.exports._copySingle (/Users/timkelty/Repos/generator-craft-plugin/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:52:24)
    at EditionInterface.<anonymous> (/Users/timkelty/Repos/generator-craft-plugin/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:37:10)
    at Array.forEach (native)
    at EditionInterface.exports.copy (/Users/timkelty/Repos/generator-craft-plugin/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:34:9)
    at EditionInterface.module.exports [as copyTpl] (/Users/timkelty/Repos/generator-craft-plugin/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:9:8)
    at module.exports.yeoman.generators.Base.extend.writing.pluginFiles (/Users/timkelty/Repos/generator-craft-plugin/app/index.js:125:15)
    at /Users/timkelty/Repos/generator-craft-plugin/node_modules/yeoman-generator/lib/base.js:406:16
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by markjbyrne81** [comment] 2015-01-23 11:34
Is there an ETA for a fix for this issue?

**Comment by markjbyrne81** [comment] 2015-01-23 12:59
So far I have traced this issue to _copySingle() in copy.js

on line 57 you call file.contents which returns null every time.  Something tells me that the file var on line 43 is not being resolved correctly but I haven't gotten any further in my investigation.

**Comment by Tokimon** [comment] 2015-01-27 16:55
I had this error as well and after some digging it seems that the `{ nodir: true }` glob option in 'mem-fs-editor/actions/copy.js' (line 33) doesn't work. Because the following `var files = glob.sync(from, globOptions)` (line 34) consists of both files and folders, which in turn breaks the processing call in the `_copySingle` method (line 60) as it expects every entry to be a file.

**Comment by blai** [comment] 2015-01-27 17:49
@Tokimon Would you be able to come up with a test case that represent your error scenario? I'd be easier to understand your problem in that case.

**Comment by markjbyrne81** [comment] 2015-01-28 14:06
I can confirm @Tokimon issue.  

mem-fs-editor\actions\copyTpl.js does not include a globOptions property in the 3rd argument when it calls ``` this.copy ``` (line 9).  This means that when ``` _.extend ``` is called in mem-fs-editor\actions\copy.js (line 30) options.globOptions is undefined and in turn ``` _.extend ``` returns undefined instead of ``` {  nodir: true } ```

This then results in directories being returned from the ``` glob.sync() ``` call (line 31) which in turn causes the ``` process ``` function in mem-fs-editor\actions\copyTpl.js (line 11) to fail when it calls ``` contents.toString().```

I believe that a change to \actions\copyTpl.js (shown below) could correct this issue.  It just adds a globOptions property (set to and empty object) to the object being passed in the 3rd argument of ``` this.copy ```

```
'use strict';

var path = require('path');
var _ = require('lodash');

module.exports = function (from, to, context, tplSettings) {
  context = context || {};
  tplSettings = tplSettings || {};
  this.copy(from, to, {
    process: function (contents) {
      return _.template(contents.toString(), context, tplSettings);
    },
    globOptions: {}
  });
};
```

**Comment by SBoudrias** [comment] 2015-01-28 16:15
Hey guys, seems you found the issue. So a PR is welcomed to fix it! (with unit test)

**Comment by markjbyrne81** [comment] 2015-01-28 17:00
Hey @SBoudrias .  I have never done a PR before but I will happily give it a go later tonight.

**Closed** 2015-01-28 20:00 UTC
